### ISSUE TITLE
Notifications are displayed double

### ISSUE THREAD

**Issue by bs-baba** [Itvisors/mendix-FeedbackNotification#1]
Hi,

Place this widget on both a non-popup page (Page A) and a popup page that is navigated from Page A (Page B).
When I try to display the notification on page B, the widget on page A also displays the notification with the same content.
Is this correct behavior? We want to display only the page B notification in this case.

If we delete one of the widgets, there will be only one notification. But we cannot do so because the two widgets have different property values (such as Position) set.

![image](https://user-images.githubusercontent.com/38234320/189889283-7c284678-b976-47fc-bd95-8503f9957475.png)

Thank you,

**Comment by bs-baba** [comment]
Implementing the widget to enable "Multi containers support" worked fine.
https://fkhadra.github.io/react-toastify/multi-containers

**Comment by jeuhen** [comment]
Hi bs-baba,

Great that you found the solution for this and thanks for sharing.
If you want you can always create a merge request such that others can also use this functionality and if I add something else, you can just update without adding your custom code.
Is enableMultiContainer the only thing you added?
Then I will add this in a future version.

Kind regards,

Johan
